### ISSUE TITLE
Python 3.11+: module 'asyncio' has no attribute 'coroutine'

### ISSUE THREAD

**Issue by djuarezg** [jupyterlab/jupyterlab-git#1261]
![image](https://github.com/jupyterlab/jupyterlab-git/assets/34030545/f37f5603-f6c3-4e4d-89d5-5b0153b15577)

Running with jupyter/scipy-notebook:python-3.11.3 and probably related to https://stackoverflow.com/questions/74345065/attributeerror-module-asyncio-has-no-attribute-coroutine-in-python-3-11

**Comment by firai** [comment]
It seems like the latest `pexpect` `master` was released a month ago?

**Comment by fcollonval** [comment]
Thanks a lot for the news @firai 
Indeed the issue should be fixed now --> closing this one

**Comment by bluechallenge** [comment]
> Thanks a lot for the news @firai Indeed the issue should be fixed now --> closing this one

@fcollonval Sorry, may I know some more details about how to fix this issue?

**Comment by fcollonval** [comment]
@bluechallenge could you check the pexpect version you are using?
It should be 4.9+ to work with python 3.11+

**Comment by bluechallenge** [comment]
> @bluechallenge could you check the pexpect version you are using? It should be 4.9+ to work with python 3.11+

Thanks a lot @fcollonval. It works well now after upgrading pexpect from 4.8 to [4.9](https://pypi.org/project/pexpect/) via "pip install pexpect==4.9.0".

**Comment by Kaschmiri** [comment]
So anyone running jupyerlab on conda environments is going to run into this issue because pexpect v 4.8.0 is the latest version available on conda forge.
